version: '3'

services: 
  web-admin-makan-di:
    container_name: makan-di.web-admin
    image: makan-di.web-admin:dev
    restart: always
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3200:99